version: '3'
services:
  web:
    build: .
    # networks:
    #   - web-network
    ports:
      - "8080:8080"
    volumes:
      - ./database.db:/app/database.db

# networks:
#   web-network:
#     external: true
#     name: rabbitmq_network