// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "João Pedro Limão",
            "email": "joao.limao.701@ufrn.edu.br"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/brands": {
            "get": {
                "description": "Get phone brands list.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PhoneList"
                ],
                "summary": "Get phone brands list.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/phonelist.Brand"
                            }
                        }
                    }
                }
            }
        },
        "/buy": {
            "post": {
                "description": "Buy new insurance.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "Buy new insurance.",
                "parameters": [
                    {
                        "description": "Buy a new insurance",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/simulation.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/simulation.BuyResponse"
                        }
                    }
                }
            }
        },
        "/cancel": {
            "post": {
                "description": "Cancel insurance.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Insurance Management"
                ],
                "summary": "Cancel insurance.",
                "parameters": [
                    {
                        "description": "Send user id to cancel insurance",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cancel.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cancel.Response"
                        }
                    }
                }
            }
        },
        "/insurance": {
            "post": {
                "description": "Get Insurance information.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Insurance Management"
                ],
                "summary": "Get Insurance information.",
                "parameters": [
                    {
                        "description": "Send user id to get insurance information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/getinsurance.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getinsurance.Response"
                        }
                    }
                }
            }
        },
        "/models": {
            "get": {
                "description": "Get phone models list.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PhoneList"
                ],
                "summary": "Get phone models list.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "A brand code of cellphone",
                        "name": "cellphone-brand-code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/phonelist.ModelResponse"
                        }
                    }
                }
            }
        },
        "/simulation": {
            "post": {
                "description": "Show simulation data.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "Show simulation data.",
                "parameters": [
                    {
                        "description": "Resquest to simulation info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/simulation.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/simulation.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cancel.Request": {
            "type": "object",
            "properties": {
                "user-id": {
                    "type": "string"
                }
            }
        },
        "cancel.Response": {
            "type": "object",
            "properties": {
                "insurance-status": {
                    "type": "string"
                }
            }
        },
        "getinsurance.Request": {
            "type": "object",
            "properties": {
                "user-id": {
                    "type": "string"
                }
            }
        },
        "getinsurance.Response": {
            "type": "object",
            "properties": {
                "cellphone-brand": {
                    "type": "string"
                },
                "cellphone-model": {
                    "type": "string"
                },
                "franchise": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "validity": {
                    "type": "string"
                },
                "value-per-month": {
                    "type": "number"
                }
            }
        },
        "phonelist.Brand": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "phonelist.Model": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "phonelist.ModelResponse": {
            "type": "object",
            "properties": {
                "brand-code": {
                    "type": "string"
                },
                "brand-name": {
                    "type": "string"
                },
                "list-cellphone-model": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/phonelist.Model"
                    }
                }
            }
        },
        "simulation.BuyResponse": {
            "type": "object",
            "properties": {
                "cellphone-brand-code": {
                    "type": "string"
                },
                "cellphone-model-code": {
                    "type": "string"
                },
                "franchise": {
                    "type": "number"
                },
                "payment-id": {
                    "type": "string"
                },
                "user-id": {
                    "type": "string"
                },
                "value-per-month": {
                    "type": "number"
                }
            }
        },
        "simulation.Request": {
            "type": "object",
            "required": [
                "cellphone-brand-code",
                "cellphone-model-code",
                "user-id"
            ],
            "properties": {
                "cellphone-brand-code": {
                    "type": "string"
                },
                "cellphone-model-code": {
                    "type": "string"
                },
                "user-id": {
                    "type": "string"
                }
            }
        },
        "simulation.Response": {
            "type": "object",
            "properties": {
                "cellphone-brand-code": {
                    "type": "string"
                },
                "cellphone-model-code": {
                    "type": "string"
                },
                "franchise": {
                    "type": "number"
                },
                "user-id": {
                    "type": "string"
                },
                "value-per-month": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8001",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "ms-insurance",
	Description:      "MS with insurance features",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
